[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/nalej/derrors"
    version="v2.0.0"

[[constraint]]
    name="github.com/nalej/authx-interceptors"
    branch="master"

[[constraint]]
    name="github.com/nalej/grpc-authx-go"
    version="=v0.0.48"

[[constraint]]
    name="github.com/nalej/grpc-inventory-manager-go"
    version="v0.0.1"

[[constraint]]
                        name="github.com/nalej/grpc-eic-api-go"
                        version="v0.0.3"