###
# EIC API
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: eic-api
  name: eic-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: eic-api
  template:
    metadata:
      labels:
        cluster: management
        component: eic-api
    spec:
      containers:
      - name: eic-api
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/eic-api:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
