###
# EIC API
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: eic-api
  name: eic-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: eic-api
  template:
    metadata:
      labels:
        cluster: management
        component: eic-api
    spec:
      volumes:
      - name: authx-config
        configMap:
          name: eic-api-authx-config
      containers:
      - name: eic-api
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/eic-api:__NPH_VERSION
        imagePullPolicy: Always
        volumeMounts:
        - name: authx-config
          mountPath: "/nalej/config"
          readOnly: true
        args:
        - "run"
        - "--debug"
        - "--inventoryManagerAddress=inventory-manager.__NPH_NAMESPACE:5510"
        - "--authHeader=authorization"
        - "--authSecret=$(AUTH_SECRET)"
        - "--authConfigPath=/nalej/config/authx-config.json"
        - "--authxAddress=authx.__NPH_NAMESPACE:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
