kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: management
    component: eic-api
  name: eic-api-authx-config
  namespace: __NPH_NAMESPACE
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/eic_api.EIC/Join":{"must":["APIKEY"]}
      }
    }
